import type { Metadata } from "next";
import { Noto_Serif_Georgian } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/footer";

const notoSerifGeorgian = Noto_Serif_Georgian({
  variable: "--noto-serif-georgian",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSerifGeorgian.variable}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
